---
- hosts: devstack
  gather_facts: False
  vars:
    devstack_repo: git://github.com/openstack-dev/devstack.git
    branch: stable/grizzly
    devstack_branch: "{{ branch }}"
  tasks:
    - name: git
      apt: pkg=git
      sudo: True

    - name: checkout devstack
      git: repo={{ devstack_repo }} dest=/home/vagrant/devstack version={{ devstack_branch }}

    - name: localrc
      template: src=templates/localrc dest=/home/vagrant/devstack/localrc

    - name: source openrc
      lineinfile: dest=/home/vagrant/.profile regexp=".*openrc" line='. /home/vagrant/devstack/openrc'


