---
- hosts: devstack
  vars:
    devstack_repo: git://github.com/openstack-dev/devstack.git
    public_ip: 192.168.27.100
    public_gateway: 192.168.50.2
    external_network: eth2
    floating_range: 192.168.50.0/24
    floating_allocation_pool: "start=192.168.50.10,end=192.168.50.50"
    fully_automated: True

  tasks:
    - name: install packages
      apt: "pkg={{ item }} update_cache=yes"
      sudo: True
      with_items:
       - git

    - name: checkout devstack
      git: "repo={{ devstack_repo }} dest=/home/vagrant/devstack"

    - name: localrc
      template: src=templates/localrc dest=/home/vagrant/devstack/localrc

    - name: source openrc in profile
      lineinfile: dest=/home/vagrant/.profile regexp=".*openrc" line='. /home/vagrant/devstack/openrc'

    - name: run devstack
      shell: cd devstack; ./stack.sh
      when: fully_automated

    - name: Add external network interface to br-ex
      command: ovs-vsctl add-port br-ex {{ external_network }}
      sudo: True
      when: fully_automated

    - name: Remove IP address from external network interface
      command: ip addr flush dev {{ external_network }}
      sudo: True
      when: fully_automated

    - name: set external interface up
      command: ip link set dev {{ external_network }} up
      sudo: True
      when: fully_automated

    - name: set external interface to promiscuous mode
      command: ip link set dev {{ external_network }} promisc on
      sudo: True
      when: fully_automated

