---
- hosts: devstack
  gather_facts: False
  vars:
    devstack_repo: git://github.com/bigswitch/devstack.git
    floodlight_repo: git://github.com/floodlight/floodlight.git
    devstack_branch: floodlight/folsom
    floodlight_src_dir: /home/vagrant/floodlight-master

  tasks:
    - name: packages
      apt: pkg={{ item }} update_cache=yes
      sudo: True
      with_items:
        - git
        - zip
        - default-jdk
        - ant

    - name: checkout floodlight
      git: repo={{ floodlight_repo }} dest={{ floodlight_src_dir }}

    - name: build floodlight
      command: ant chdir={{ floodlight_src_dir }} creates={{ floodlight_src_dir }}/target/floodlight.jar

    - name: checkout devstack
      git: repo={{ devstack_repo }} dest=/home/vagrant/devstack version={{ devstack_branch }}

    - name: set location of controller in localrc
      lineinfile: >
        dest=/home/vagrant/devstack/localrc
        regexp="^BS_FL_CONTROLLERS_PORT=.*"
        line="BS_FL_CONTROLLERS_PORT=localhost:8080"

    - name: use eth1 in localrc
      lineinfile: >
        dest=/home/vagrant/devstack/localrc
        regexp="^HOST_IP_IFACE=.*"
        line="HOST_IP_IFACE=eth1"

    - name: source openrc
      lineinfile: dest=/home/vagrant/.profile regexp=".*openrc" line='. /home/vagrant/devstack/openrc'
